version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - "8099:8091"
      - "453:443"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - meganetwork

  php:
    build:
      context: ./docker/php
    container_name: app-php
    volumes:
      - ./app:/var/www/html
    networks:
      - meganetwork

  db:
    platform: linux/x86_64
    image: mysql:5.6.47
    container_name: app-db
    ports:
      - "3386:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./docker/database/base.sql:/docker-entrypoint-initdb.d/base.sql:ro
    networks:
      - meganetwork

networks:
  meganetwork:
    driver: bridge