version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3386:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./docker/database/base.sql:/docker-entrypoint-initdb.d/base.sql:ro
