version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - "8099:8090"
      - "453:443"
    volumes:
      - ./:/var/www

  db:
    platform: linux/x86_64
    image: mysql:5.6.47
    container_name: app-db
    ports:
      - "3386:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql:ro
